// Code generated by core-cli. DO NOT EDIT.

package main

import (
	"fmt"
	"net/http"
	"net/http/httputil"
	"net/url"
	"os"
	"strings"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
)

func main() {
	e := echo.New()
	e.HideBanner = true
	e.Use(middleware.CORSWithConfig(middleware.CORSConfig{
		AllowOrigins: []string{"*"},
		AllowMethods: []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
	}))

	// Health
	e.GET("/health", func(c echo.Context) error {
		return c.String(200, "ok")
	})

	// Public routes (no JWT, no RBAC)

	// Protected routes (JWT + RBAC)

	e.POST("/api/users/auth/login", proxyHandler("users-service", 8081, "/api/users", "/api"))
	e.POST("/api/users/auth/register", proxyHandler("users-service", 8081, "/api/users", "/api"))
	e.GET("/api/users/users", proxyHandler("users-service", 8081, "/api/users", "/api"), AuthMiddleware)

	e.GET("/api/users/users/:id", proxyHandler("users-service", 8081, "/api/users", "/api"), AuthMiddleware)

	e.POST("/api/users/users", proxyHandler("users-service", 8081, "/api/users", "/api"), AuthMiddleware)

	e.PUT("/api/users/users/:id", proxyHandler("users-service", 8081, "/api/users", "/api"), AuthMiddleware)

	e.DELETE("/api/users/users/:id", proxyHandler("users-service", 8081, "/api/users", "/api"), AuthMiddleware)

	e.POST("/api/users/users/:id/restore-password", proxyHandler("users-service", 8081, "/api/users", "/api"), AuthMiddleware)

	e.GET("/api/users/profile", proxyHandler("users-service", 8081, "/api/users", "/api"), AuthMiddleware)

	e.PUT("/api/users/profile", proxyHandler("users-service", 8081, "/api/users", "/api"), AuthMiddleware)

	e.GET("/api/users/roles", proxyHandler("users-service", 8081, "/api/users", "/api"), AuthMiddleware)

	e.POST("/api/users/roles", proxyHandler("users-service", 8081, "/api/users", "/api"), AuthMiddleware)

	e.GET("/api/users/audit-logs", proxyHandler("users-service", 8081, "/api/users", "/api"), AuthMiddleware)










































	// User-owned custom handler routes (users auth domain)
	RegisterUserRoutes(e)

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	e.Logger.Fatal(e.Start(":" + port))
}

// proxyHandler creates a reverse proxy that forwards requests to the target service.
// If replacePrefix is set, it is replaced with toPrefix in the upstream path.
// This handles the gateway's service-name prefix (e.g. /api/users → /api).
func proxyHandler(service string, port int, replacePrefix, toPrefix string) echo.HandlerFunc {
	target := &url.URL{Scheme: "http", Host: fmt.Sprintf("%s:%d", service, port)}
	proxy := httputil.NewSingleHostReverseProxy(target)
	originalDirector := proxy.Director
	proxy.Director = func(req *http.Request) {
		originalDirector(req)
		if replacePrefix != "" {
			req.URL.Path = strings.Replace(req.URL.Path, replacePrefix, toPrefix, 1)
		}
	}
	proxy.ModifyResponse = func(r *http.Response) error {
		return nil  // noop, just enables the hook
	}
	return func(c echo.Context) error {
		// Use the underlying ResponseWriter directly to avoid Echo response wrapper issues
		proxy.ServeHTTP(c.Response().Writer, c.Request())
		return nil
	}
}
