-- Code generated by core-cli. DO NOT EDIT.
-- NOTE: Re-ordered to respect FK dependencies. Reserved words quoted with "".

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- Schema for users-service
CREATE SCHEMA IF NOT EXISTS users_service;

CREATE TABLE IF NOT EXISTS users_service.loginrequest (
  email VARCHAR(255) NOT NULL
  , password VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS users_service.registerrequest (
  email VARCHAR(255) NOT NULL
  , password VARCHAR(255) NOT NULL
  , fullname VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS users_service.healthresponse (
  status VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS users_service.rootresponse (
  message VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS users_service.role (
  id UUID PRIMARY KEY NOT NULL
  , name VARCHAR(255) NOT NULL
  , description VARCHAR(255) NOT NULL
  , permissions TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS users_service."user" (
  id UUID PRIMARY KEY NOT NULL
  , email VARCHAR(255) NOT NULL
  , passwordhash VARCHAR(255) NOT NULL
  , fullname VARCHAR(255) NOT NULL
  , phone VARCHAR(255) NULL
  , roleid UUID NOT NULL
  , isactive TEXT NOT NULL
  , organizationid UUID NOT NULL
  , createdat TIMESTAMP NOT NULL
  , updatedat TIMESTAMP NOT NULL
  , firstlogin BOOLEAN NOT NULL DEFAULT TRUE
);


-- Password reset tokens (one-time use, SHA-256 hash of random token)
CREATE TABLE IF NOT EXISTS users_service.password_reset_tokens (
  id UUID PRIMARY KEY
  , user_id UUID NOT NULL REFERENCES users_service."user"(id) ON DELETE CASCADE
  , token_hash TEXT NOT NULL
  , expires_at TIMESTAMPTZ NOT NULL
  , used_at TIMESTAMPTZ NULL
  , created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_token_hash ON users_service.password_reset_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user_id ON users_service.password_reset_tokens(user_id);



CREATE TABLE IF NOT EXISTS users_service.loginresponse (
  token VARCHAR(255) NOT NULL
  , "user" UUID NOT NULL
  , role VARCHAR(255) NOT NULL
  , organizationid UUID NOT NULL
  , permissions TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS users_service.userprofile (
  id UUID PRIMARY KEY NOT NULL
  , userid UUID NOT NULL
  , avatarurl VARCHAR(255) NOT NULL
  , bio TEXT NOT NULL
  , preferences TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS users_service.auditlog (
  id UUID PRIMARY KEY NOT NULL
  , entitytype VARCHAR(255) NOT NULL
  , entityid UUID NOT NULL
  , action VARCHAR(255) NOT NULL
  , oldvalue TEXT NOT NULL
  , newvalue TEXT NOT NULL
  , changedby UUID NOT NULL
  , changedat TIMESTAMP NOT NULL
  , ipaddress VARCHAR(255) NOT NULL
);

-- Seed default roles
INSERT INTO users_service.role (id, name, description, permissions) VALUES
('e0000000-0000-0000-0000-000000000001', 'admin', 'Super Administrador', '{"can_manage_users": true, "can_write_values": true, "can_approve_good_practices": true}'),
('e0000000-0000-0000-0000-000000000002', 'user', 'Usuario Estándar', '{"can_manage_users": false, "can_write_values": true, "can_approve_good_practices": false}')
ON CONFLICT (id) DO NOTHING;

-- Seed default generic admin user (password: admin123)
INSERT INTO users_service."user" (id, email, passwordhash, fullname, roleid, isactive, organizationid, createdat, updatedat, firstlogin) VALUES
('f0000000-0000-0000-0000-000000000001', 'admin@example.com', '$2b$10$bgq.hqvdYYntjkKOqVV8KOgXVvkxjeTzjvI1J857KrDTHDq0UNJPG', 'Administrador', 'e0000000-0000-0000-0000-000000000001', 'true', '00000000-0000-0000-0000-000000000000', NOW(), NOW(), false)
ON CONFLICT (id) DO NOTHING;



