// Code generated by core-cli. DO NOT EDIT.

package grpcadapter

import (
	"fmt"
	"net"

	"google.golang.org/grpc"
)

// EvaluationsServiceGRPCServer implements the gRPC server for the evaluations-service service.
type EvaluationsServiceGRPCServer struct {
	port int
}

// NewEvaluationsServiceGRPCServer creates a new gRPC server for evaluations-service.
func NewEvaluationsServiceGRPCServer(port int) *EvaluationsServiceGRPCServer {
	return &EvaluationsServiceGRPCServer{port: port}
}

// Start launches the gRPC server. In production, register your service
// implementation methods on this struct and register with a grpc.Server.
func (s *EvaluationsServiceGRPCServer) Start() error {
	lis, err := net.Listen("tcp", fmt.Sprintf(":%d", s.port))
	if err != nil {
		return fmt.Errorf("failed to listen on port %d: %w", s.port, err)
	}
	srv := grpc.NewServer()
	// Register your generated gRPC service impl here:
	// RegisterEvaluationsServiceServiceServer(srv, s)
	fmt.Printf("evaluations-service gRPC server listening on :%d\n", s.port)
	return srv.Serve(lis)
}
