// Code generated by core-cli. DO NOT EDIT.

package portin

import (
	"context"

	"users-service/internal/domain"
)


// PostAuthLoginRequest is the input for the POST /auth/login endpoint.
type PostAuthLoginRequest struct {
	Body *domain.LoginRequest
	// Path and query params go here
}

// PostAuthLoginResponse is the output for the POST /auth/login endpoint.
type PostAuthLoginResponse struct {
	Item *domain.LoginResponse
}

// PostAuthRegisterRequest is the input for the POST /auth/register endpoint.
type PostAuthRegisterRequest struct {
	Body *domain.RegisterRequest
	// Path and query params go here
}

// PostAuthRegisterResponse is the output for the POST /auth/register endpoint.
type PostAuthRegisterResponse struct {
	Item *domain.User
}

// GetUsersRequest is the input for the GET /users endpoint.
type GetUsersRequest struct {
	// Path and query params go here
}

// GetUsersResponse is the output for the GET /users endpoint.
type GetUsersResponse struct {
	Items []*domain.User
	Total int
}

// GetUserRequest is the input for the GET /users/{id} endpoint.
type GetUserRequest struct {
	ID string
}

// GetUserResponse is the output for the GET /users/{id} endpoint.
type GetUserResponse struct {
	Item *domain.User
}

// PostUsersRequest is the input for the POST /users endpoint.
type PostUsersRequest struct {
	Body *domain.User
	// Path and query params go here
}

// PostUsersResponse is the output for the POST /users endpoint.
type PostUsersResponse struct {
	Item *domain.User
}

// UpdateUserRequest is the input for the PUT /users/{id} endpoint.
type UpdateUserRequest struct {
	Body *domain.User
	// Path and query params go here
}

// UpdateUserResponse is the output for the PUT /users/{id} endpoint.
type UpdateUserResponse struct {
	Item *domain.User
}

// DeleteUserRequest is the input for the DELETE /users/{id} endpoint.
type DeleteUserRequest struct {
	ID string
}

// DeleteUserResponse is the output for the DELETE /users/{id} endpoint.
type DeleteUserResponse struct {
}

// GetProfileRequest is the input for the GET /profile endpoint.
type GetProfileRequest struct {
	UserID string
}

// GetProfileResponse is the output for the GET /profile endpoint.
type GetProfileResponse struct {
	Item *domain.User
}

// PutProfileRequest is the input for the PUT /profile endpoint.
type PutProfileRequest struct {
	Body *domain.UserProfile
	// Path and query params go here
}

// PutProfileResponse is the output for the PUT /profile endpoint.
type PutProfileResponse struct {
	Item *domain.UserProfile
}

// GetRolesRequest is the input for the GET /roles endpoint.
type GetRolesRequest struct {
	// Path and query params go here
}

// GetRolesResponse is the output for the GET /roles endpoint.
type GetRolesResponse struct {
	Items []*domain.Role
	Total int
}

// PostRolesRequest is the input for the POST /roles endpoint.
type PostRolesRequest struct {
	Body *domain.Role
	// Path and query params go here
}

// PostRolesResponse is the output for the POST /roles endpoint.
type PostRolesResponse struct {
	Item *domain.Role
}

// GetAuditLogsRequest is the input for the GET /audit-logs endpoint.
type GetAuditLogsRequest struct {
	// Path and query params go here
}

// GetAuditLogsResponse is the output for the GET /audit-logs endpoint.
type GetAuditLogsResponse struct {
	Items []*domain.AuditLog
	Total int
}


// UsersServiceUseCase is the driving port — the contract every inbound adapter calls.
// Implement this in internal/usecases/logic.go.
type UsersServiceUseCase interface {
	PostAuthLogin(ctx context.Context, req PostAuthLoginRequest) (PostAuthLoginResponse, error)
	PostAuthRegister(ctx context.Context, req PostAuthRegisterRequest) (PostAuthRegisterResponse, error)
	GetUsers(ctx context.Context, req GetUsersRequest) (GetUsersResponse, error)
	GetUser(ctx context.Context, req GetUserRequest) (GetUserResponse, error)
	PostUsers(ctx context.Context, req PostUsersRequest) (PostUsersResponse, error)
	UpdateUser(ctx context.Context, req UpdateUserRequest) (UpdateUserResponse, error)
	DeleteUser(ctx context.Context, req DeleteUserRequest) (DeleteUserResponse, error)
	GetProfile(ctx context.Context, req GetProfileRequest) (GetProfileResponse, error)
	PutProfile(ctx context.Context, req PutProfileRequest) (PutProfileResponse, error)
	GetRoles(ctx context.Context, req GetRolesRequest) (GetRolesResponse, error)
	PostRoles(ctx context.Context, req PostRolesRequest) (PostRolesResponse, error)
	GetAuditLogs(ctx context.Context, req GetAuditLogsRequest) (GetAuditLogsResponse, error)
	GetUserHistory(ctx context.Context, id string) ([]*domain.UserHistory, error)
	ForgotPassword(ctx context.Context, email string) error
	ResetPassword(ctx context.Context, token string, newPassword string) error
	ChangePassword(ctx context.Context, userID, currentPassword, newPassword string) error
	CompleteOnboarding(ctx context.Context, userID, newPassword string) error
	RestorePasswordForUser(ctx context.Context, id string) error
}

// UsersServiceEventHandler is the driving port for async event consumers.
// Implement this in internal/usecases/logic.go alongside UsersServiceUseCase.
type UsersServiceEventHandler interface {
	HandleUserCreated(ctx context.Context, payload []byte) error
	HandleUserUpdated(ctx context.Context, payload []byte) error
	HandleUserDeleted(ctx context.Context, payload []byte) error
}

