// Code generated by core-cli. DO NOT EDIT.

// Entity types derived from the service schema.
// These types are kept in sync with the backend automatically.

export interface LoginRequest {
  Email: string;
  Password: string;
}

export interface LoginResponse {
  Token: string;
  User: string;
  Role: string;
  DestinationID: string;
  Permissions: any;
}

export interface RegisterRequest {
  Email: string;
  Password: string;
  FullName: string;
}

export interface HealthResponse {
  Status: string;
}

export interface RootResponse {
  Message: string;
}

export interface UserProfile {
  ID: string;
  UserID: string;
  AvatarURL: string;
  Bio: string;
  Preferences: any;
}

export interface User {
  ID: string;
  Email: string;
  PasswordHash: string;
  FullName: string;
  RoleID: string;
  IsActive: boolean;
  DestinationID: string;
  CreatedAt: string;
  UpdatedAt: string;
}

export interface Role {
  ID: string;
  Name: string;
  Description: string;
  Permissions: any;
}

export interface AuditLog {
  ID: string;
  EntityType: string;
  EntityID: string;
  Action: string;
  OldValue: any;
  NewValue: any;
  ChangedBy: string;
  ChangedAt: string;
  IPAddress: string;
}
