// Code generated by core-cli. DO NOT EDIT.

package httpadapter

import (
	"net/http"
	"database/sql"
	"log"
	"strings"
	"users-service/internal/domain"

	"github.com/google/uuid"
	"github.com/labstack/echo/v4"

	portin "users-service/internal/ports/in"
)

// Handler wires the HTTP layer to the use case.
type Handler struct {
	uc portin.UsersServiceUseCase
	db *sql.DB
}

// NewHandler creates a new HTTP handler and registers all routes on e.
func NewHandler(e *echo.Group, uc portin.UsersServiceUseCase, db *sql.DB) *Handler {
	h := &Handler{
		uc: uc,
		db: db,
	}
	h.registerRoutes(e)
	return h
}

func (h *Handler) registerRoutes(e *echo.Group) {
	e.POST("/auth/login", h.handlePostAuthLogin)
	e.POST("/auth/register", h.handlePostAuthRegister)
	e.GET("/users", h.handleGetUsers)
	e.GET("/users/:id", h.handleGetUser)
	e.POST("/users", h.handlePostUsers)
	e.PUT("/users/:id", h.handleUpdateUser)
	e.DELETE("/users/:id", h.handleDeleteUser)
	e.POST("/users/:id/restore-password", h.handleRestorePassword)
	e.GET("/profile", h.handleGetProfile)
	e.PUT("/profile", h.handlePutProfile)
	e.GET("/roles", h.handleGetRoles)
	e.POST("/roles", h.handlePostRoles)
	e.GET("/audit-logs", h.handleGetAuditLogs)
	e.GET("/user/:id/history", h.handleGetUserHistory)
}

func (h *Handler) handlePostAuthLogin(c echo.Context) error {
	req := portin.PostAuthLoginRequest{}
	if err := c.Bind(&req.Body); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
	}
	resp, err := h.uc.PostAuthLogin(c.Request().Context(), req)
	if err != nil {
		errMsg := err.Error()
		if strings.Contains(errMsg, "invalid email or password") ||
			strings.Contains(errMsg, "user account is disabled") {
			// Never expose whether the email exists or why — generic message
			return echo.NewHTTPError(http.StatusUnauthorized, "credenciales inválidas")
		}
		return echo.NewHTTPError(http.StatusInternalServerError, "error interno")
	}
	return c.JSON(http.StatusOK, resp.Item)
}

func (h *Handler) handlePostAuthRegister(c echo.Context) error {
	req := portin.PostAuthRegisterRequest{}
	if err := c.Bind(&req.Body); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
	}
	resp, err := h.uc.PostAuthRegister(c.Request().Context(), req)
	if err != nil {
		return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
	}
	return c.JSON(http.StatusOK, resp)
}

func (h *Handler) handleGetUsers(c echo.Context) error {
	req := portin.GetUsersRequest{}
	resp, err := h.uc.GetUsers(c.Request().Context(), req)
	if err != nil {
		return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
	}
	return c.JSON(http.StatusOK, resp)
}

func (h *Handler) handleGetUser(c echo.Context) error {
	req := portin.GetUserRequest{ID: c.Param("id")}
	if req.ID == "" {
		return echo.NewHTTPError(http.StatusBadRequest, "id is required")
	}
	resp, err := h.uc.GetUser(c.Request().Context(), req)
	if err != nil {
		return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
	}
	if resp.Item == nil {
		return echo.NewHTTPError(http.StatusNotFound, "user not found")
	}
	return c.JSON(http.StatusOK, resp)
}

func (h *Handler) handlePostUsers(c echo.Context) error {
	req := portin.PostUsersRequest{}
	if err := c.Bind(&req.Body); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
	}
	log.Printf("[handlePostUsers] body=%+v", req.Body)
	resp, err := h.uc.PostUsers(c.Request().Context(), req)
	if err != nil {
		log.Printf("[handlePostUsers] PostUsers ERROR: %v", err)
		return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
	}
	log.Printf("[handlePostUsers] PostUsers SUCCESS, resp.Item=%+v", resp.Item)
	return c.JSON(http.StatusOK, resp)
}

func (h *Handler) handleUpdateUser(c echo.Context) error {
	req := portin.UpdateUserRequest{}
	if err := c.Bind(&req.Body); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
	}
	// Set the ID from the URL path param
	id, err := uuid.Parse(c.Param("id"))
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, "invalid user id")
	}
	if req.Body == nil {
		req.Body = &domain.User{}
	}
	req.Body.ID = id
	resp, err := h.uc.UpdateUser(c.Request().Context(), req)
	if err != nil {
		return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
	}
	return c.JSON(http.StatusOK, resp)
}

func (h *Handler) handleDeleteUser(c echo.Context) error {
	req := portin.DeleteUserRequest{ID: c.Param("id")}
	if req.ID == "" {
		return echo.NewHTTPError(http.StatusBadRequest, "id is required")
	}
	resp, err := h.uc.DeleteUser(c.Request().Context(), req)
	if err != nil {
		return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
	}
	return c.JSON(http.StatusOK, resp)
}

func (h *Handler) handleGetProfile(c echo.Context) error {
	userID, ok := c.Get("user_id").(string)
	if !ok || userID == "" {
		return echo.NewHTTPError(http.StatusUnauthorized, "user not authenticated")
	}
	req := portin.GetProfileRequest{UserID: userID}
	resp, err := h.uc.GetProfile(c.Request().Context(), req)
	if err != nil {
		return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
	}
	return c.JSON(http.StatusOK, resp)
}

func (h *Handler) handlePutProfile(c echo.Context) error {
	userID, ok := c.Get("user_id").(string)
	if !ok || userID == "" {
		return echo.NewHTTPError(http.StatusUnauthorized, "user not authenticated")
	}
	req := portin.PutProfileRequest{}
	if err := c.Bind(&req.Body); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
	}
	if req.Body == nil {
		req.Body = &domain.UserProfile{}
	}
	uid, err := uuid.Parse(userID)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, "invalid user id")
	}
	req.Body.UserID = uid
	resp, err := h.uc.PutProfile(c.Request().Context(), req)
	if err != nil {
		return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
	}
	return c.JSON(http.StatusOK, resp)
}

func (h *Handler) handleRestorePassword(c echo.Context) error {
	id := c.Param("id")
	if id == "" {
		return echo.NewHTTPError(http.StatusBadRequest, "id is required")
	}
	if err := h.uc.RestorePasswordForUser(c.Request().Context(), id); err != nil {
		return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
	}
	return c.JSON(http.StatusOK, map[string]string{"message": "password restored"})
}

func (h *Handler) handleGetRoles(c echo.Context) error {
	req := portin.GetRolesRequest{}
	resp, err := h.uc.GetRoles(c.Request().Context(), req)
	if err != nil {
		return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
	}
	return c.JSON(http.StatusOK, resp)
}

func (h *Handler) handlePostRoles(c echo.Context) error {
	req := portin.PostRolesRequest{}
	if err := c.Bind(&req.Body); err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, err.Error())
	}
	resp, err := h.uc.PostRoles(c.Request().Context(), req)
	if err != nil {
		return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
	}
	return c.JSON(http.StatusOK, resp)
}

func (h *Handler) handleGetAuditLogs(c echo.Context) error {
	req := portin.GetAuditLogsRequest{}
	resp, err := h.uc.GetAuditLogs(c.Request().Context(), req)
	if err != nil {
		return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
	}
	return c.JSON(http.StatusOK, resp)
}















func (h *Handler) handleGetUserHistory(c echo.Context) error {
	id := c.Param("id")
	rows, err := h.db.QueryContext(c.Request().Context(), `
		SELECT history_id, entity_id, operation, old_data, new_data, changed_by, changed_at 
		FROM user_history 
		WHERE entity_id = $1 
		ORDER BY changed_at DESC`, id)
	if err != nil {
		return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
	}
	defer rows.Close()

	var history []*domain.UserHistory
	for rows.Next() {
		var hrec domain.UserHistory
		var oldData, newData sql.NullString
		if err := rows.Scan(&hrec.HistoryID, &hrec.EntityID, &hrec.Operation, &oldData, &newData, &hrec.ChangedBy, &hrec.ChangedAt); err != nil {
			return echo.NewHTTPError(http.StatusInternalServerError, err.Error())
		}
		if oldData.Valid { hrec.OldData = oldData.String }
		if newData.Valid { hrec.NewData = newData.String }
		history = append(history, &hrec)
	}
	return c.JSON(http.StatusOK, history)
}






