// Code generated by core-cli. DO NOT EDIT.

package main

import (
	"log"
	"os"
	"database/sql"
	_ "github.com/lib/pq"

	"github.com/labstack/echo/v4"

	httpadapter "users-service/internal/adapters/in/http"
	postgres "users-service/internal/adapters/out/postgres"
	"users-service/internal/usecases"
	portout "users-service/internal/ports/out"
)

func main() {
	logger := log.New(os.Stdout, "[users-service] ", log.LstdFlags)
	logger.Println("starting service...")
	// 0. Database connection
	dbURL := os.Getenv("DB_URL")
	var db *sql.DB
	if dbURL != "" {
		var err error
		db, err = sql.Open("postgres", dbURL)
		if err != nil {
			logger.Fatalf("failed to connect to database: %v", err)
		}
		defer db.Close()
	}

	// 1. Build use case (implement your logic in internal/usecases/logic.go)
	userRepo := postgres.NewUserRepo(db)
	roleRepo := postgres.NewRoleRepo(db)
	passwordResetRepo := postgres.NewPasswordResetRepo(db)
	// Email service: disabled for generic template mode
	var emailSvc portout.EmailService = nil

	frontendURL := os.Getenv("FRONTEND_URL")
	if frontendURL == "" {
		frontendURL = "http://localhost:3000"
	}

	logoURL := os.Getenv("LOGO_URL")

	uc := usecases.NewLogic(
		usecases.WithUserRepository(userRepo),
		usecases.WithRoleRepository(roleRepo),
		usecases.WithPasswordResetRepository(passwordResetRepo),
		usecases.WithEmailService(emailSvc),
		usecases.WithTemplateRenderer(nil),
		usecases.WithFrontendURL(frontendURL),
		usecases.WithLogoURL(logoURL),
	)

	// 2. Wire HTTP adapter
	e := echo.New()
	e.HideBanner = true

	// Health check
	e.GET("/health", func(c echo.Context) error {
		if db != nil {
			if err := db.Ping(); err != nil {
				return c.JSON(503, map[string]string{"status": "unhealthy", "database": "unreachable"})
			}
		}
		rabbitURL := os.Getenv("RABBIT_URL")
		if rabbitURL == "" {
			return c.JSON(503, map[string]string{"status": "unhealthy", "messaging": "disconnected"})
		}

		return c.JSON(200, map[string]string{"status": "ok"})
	})

	// Protected routes
	api := e.Group("/api")
	if os.Getenv("SKIP_AUTH") != "true" {
		api.Use(httpadapter.AuthMiddleware)
		// Audit middleware: sets audit.user_id in the session if available
		api.Use(func(next echo.HandlerFunc) echo.HandlerFunc {
			return func(c echo.Context) error {
				if db != nil {
					userID := c.Get("user_id")
					if userID != nil {
						// Set user_id in the session for audit triggers.
						// Note: This requires a transaction to be persistent during the request.
						_, _ = db.ExecContext(c.Request().Context(), "SET audit.user_id = $1", userID)
					}
				}
				return next(c)
			}
		})
	}
	httpadapter.NewHandler(api, uc, db)
	httpadapter.RegisterAuthRecoveryRoutes(api, uc)

	// 3. Start server
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	logger.Printf("listening on :%s", port)
	if err := e.Start(":" + port); err != nil {
		logger.Fatalf("server error: %v", err)
	}
}
