-- Code generated by core-cli. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS Indicator (
    id SERIAL PRIMARY KEY,
    ID VARCHAR(255),
    RequirementID VARCHAR(255),
    Code VARCHAR(255),
    Name VARCHAR(255),
    Description VARCHAR(255),
    Type VARCHAR(255),
    Criteria VARCHAR(255),
    CreatedAt VARCHAR(255),
    UpdatedAt VARCHAR(255)
);
