-- Code generated by core-cli. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS Destination (
    id SERIAL PRIMARY KEY,
    ID VARCHAR(255),
    Name VARCHAR(255),
    Country VARCHAR(255),
    SubnationalLevelID VARCHAR(255),
    TypologyID VARCHAR(255),
    PopulationRangeID VARCHAR(255),
    RegionID VARCHAR(255),
    MemberTypeID VARCHAR(255),
    Lat VARCHAR(255),
    Lng VARCHAR(255),
    IsAdhered VARCHAR(255),
    CreatedAt VARCHAR(255),
    UpdatedAt VARCHAR(255)
);
