-- Code generated by core-cli. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS Requirement (
    id SERIAL PRIMARY KEY,
    ID VARCHAR(255),
    ScopeID VARCHAR(255),
    Code VARCHAR(255),
    Name VARCHAR(255),
    Description VARCHAR(255)
);
