-- Rollback: Drop all domain tables

SET search_path TO evaluations_service;

DROP TABLE IF EXISTS dti_plan_goal CASCADE;
DROP TABLE IF EXISTS dti_plan CASCADE;
DROP TABLE IF EXISTS good_practice CASCADE;
DROP TABLE IF EXISTS action_indicator_link CASCADE;
DROP TABLE IF EXISTS action_evidence CASCADE;
DROP TABLE IF EXISTS action CASCADE;
DROP TABLE IF EXISTS indicator_message CASCADE;
DROP TABLE IF EXISTS indicator_history CASCADE;
DROP TABLE IF EXISTS indicator_value CASCADE;
DROP TABLE IF EXISTS evaluation_user CASCADE;
DROP TABLE IF EXISTS evaluation CASCADE;
DROP TABLE IF EXISTS destination CASCADE;
DROP TABLE IF EXISTS indicator CASCADE;
DROP TABLE IF EXISTS requirement CASCADE;
DROP TABLE IF EXISTS scope CASCADE;
DROP TABLE IF EXISTS axis_level CASCADE;
