-- Code generated by core-cli. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS Scope (
    id SERIAL PRIMARY KEY,
    ID VARCHAR(255),
    Axis VARCHAR(255),
    Acronym VARCHAR(255),
    Name VARCHAR(255),
    Description VARCHAR(255),
    Icon VARCHAR(255),
    SortOrder INT
);
