-- Code generated by core-cli. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS AxisLevel (
    id SERIAL PRIMARY KEY,
    ID VARCHAR(255),
    Axis VARCHAR(255),
    ObjectivePercent VARCHAR(255),
    SortOrder INT
);
