-- Code generated by core-cli. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS User (
    id SERIAL PRIMARY KEY,
    ID VARCHAR(255),
    Email VARCHAR(255),
    PasswordHash VARCHAR(255),
    FullName VARCHAR(255),
    RoleID VARCHAR(255),
    IsActive VARCHAR(255),
    CreatedAt VARCHAR(255),
    UpdatedAt VARCHAR(255)
);
