-- Code generated by core-cli. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS UserProfile (
    id SERIAL PRIMARY KEY,
    ID VARCHAR(255),
    UserID VARCHAR(255),
    AvatarURL VARCHAR(255),
    Bio VARCHAR(255),
    Preferences VARCHAR(255)
);
