-- Code generated by core-cli. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS AuditLog (
    id SERIAL PRIMARY KEY,
    ID VARCHAR(255),
    EntityType VARCHAR(255),
    EntityID VARCHAR(255),
    Action VARCHAR(255),
    OldValue VARCHAR(255),
    NewValue VARCHAR(255),
    ChangedBy VARCHAR(255),
    ChangedAt VARCHAR(255),
    IPAddress VARCHAR(255)
);
