-- Code generated by core-cli. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS Role (
    id SERIAL PRIMARY KEY,
    ID VARCHAR(255),
    Name VARCHAR(255),
    Description VARCHAR(255),
    Permissions VARCHAR(255)
);
