// Code generated by core-cli. DO NOT EDIT.

package grpcadapter

import (
	"fmt"
	"net"

	"google.golang.org/grpc"
)

// UsersServiceGRPCServer implements the gRPC server for the users-service service.
type UsersServiceGRPCServer struct {
	port int
}

// NewUsersServiceGRPCServer creates a new gRPC server for users-service.
func NewUsersServiceGRPCServer(port int) *UsersServiceGRPCServer {
	return &UsersServiceGRPCServer{port: port}
}

// Start launches the gRPC server. In production, register your service
// implementation methods on this struct and register with a grpc.Server.
func (s *UsersServiceGRPCServer) Start() error {
	lis, err := net.Listen("tcp", fmt.Sprintf(":%d", s.port))
	if err != nil {
		return fmt.Errorf("failed to listen on port %d: %w", s.port, err)
	}
	srv := grpc.NewServer()
	// Register your generated gRPC service impl here:
	// RegisterUsersServiceServiceServer(srv, s)
	fmt.Printf("users-service gRPC server listening on :%d\n", s.port)
	return srv.Serve(lis)
}
