// Code generated by core-cli. DO NOT EDIT.

package main

import (
	"fmt"
	"log"
	"os"
	"database/sql"
	_ "github.com/jackc/pgx/v5/stdlib"

	"github.com/labstack/echo/v4"

	httpadapter "evaluations-service/internal/adapters/in/http"
	"evaluations-service/internal/usecases"
)

func main() {
	logger := log.New(os.Stdout, "[evaluations-service] ", log.LstdFlags)
	logger.Println("starting service...")
	// 0. Database connection
	dbURL := os.Getenv("DB_URL")
	var db *sql.DB
	if dbURL != "" {
		var err error
		db, err = sql.Open("pgx", dbURL)
		if err != nil {
			logger.Fatalf("failed to connect to database: %v", err)
		}
		defer db.Close()
	}

	// 1. Build use case (implement your logic in internal/usecases/logic.go)
	uc := usecases.NewLogic(db)

	// 2. Wire HTTP adapter
	e := echo.New()
	e.HideBanner = true

	// Add request logging middleware
	e.Use(httpadapter.RequestLogger())

	// Health check
	e.GET("/health", func(c echo.Context) error {
		if db != nil {
			if err := db.Ping(); err != nil {
				return c.JSON(503, map[string]string{"status": "unhealthy", "database": "unreachable"})
			}
		}

		// Debug: check encoding
		var name string
		var hexName string
		if db != nil {
			_ = db.QueryRow("SELECT name FROM evaluations_service.scope WHERE id = 'a0000000-0000-0000-0000-000000000001'").Scan(&name)
			hexName = fmt.Sprintf("%x", []byte(name))
		}

		return c.JSON(200, map[string]interface{}{
			"status":   "ok",
			"db_utf8":  name,
			"db_bytes": hexName,
		})
	})

	// Login (no auth required)
	e.POST("/auth/login", httpadapter.LoginHandler)

	// Protected routes
	api := e.Group("/api")
	if os.Getenv("SKIP_AUTH") != "true" {
		api.Use(httpadapter.AuthMiddleware)
		api.Use(func(next echo.HandlerFunc) echo.HandlerFunc {
			return func(c echo.Context) error {
				if db != nil {
					userID := c.Get("user_id")
					if userID != nil {
						_, _ = db.ExecContext(c.Request().Context(), "SET audit.user_id = $1", userID)
					}
				}
				return next(c)
			}
		})
	}
	httpadapter.RegisterRoutes(api, uc, db)

	// Public routes (NO auth) - OUTSIDE the /api group
	public := e.Group("/api/public")
	public.GET("/good-practices", uc.HandlePublicGoodPractices)
	public.GET("/good-practices/:id", uc.HandlePublicGoodPractice)
	public.GET("/scopes", uc.HandleListScopes)
	public.GET("/destinations", uc.HandleListDestinations)
	public.GET("/subnational-levels", uc.HandleListSubnationalLevels)
	public.GET("/typologies", uc.HandleListDestinationTypologies)

	// 3. Start server
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}
	logger.Printf("listening on :%s", port)
	if err := e.Start(":" + port); err != nil {
		logger.Fatalf("server error: %v", err)
	}
}
