-- Code generated by core-cli. DO NOT EDIT.

-- Entity tables for users-service
-- This script is run by the postgres container on first startup.
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Generic audit log function
CREATE OR REPLACE FUNCTION fn_audit_log() RETURNS TRIGGER AS $$
BEGIN
  EXECUTE format('INSERT INTO %I_history (entity_id, operation, old_data, new_data, changed_by) VALUES ($1, $2, $3, $4, $5)', TG_TABLE_NAME)
  USING COALESCE(NEW.id, OLD.id), TG_OP, row_to_json(OLD), row_to_json(NEW), current_setting('audit.user_id', true);
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;


CREATE TABLE IF NOT EXISTS loginrequest (
  email VARCHAR(255) NOT NULL
  , password VARCHAR(255) NOT NULL
);






CREATE TABLE IF NOT EXISTS loginresponse (
  token VARCHAR(255) NOT NULL
  , user UUID NOT NULL,
  FOREIGN KEY (user) REFERENCES user(id)
  , role VARCHAR(255) NOT NULL
  , destinationid UUID NOT NULL
  , permissions TEXT NOT NULL
);






CREATE TABLE IF NOT EXISTS registerrequest (
  email VARCHAR(255) NOT NULL
  , password VARCHAR(255) NOT NULL
  , fullname VARCHAR(255) NOT NULL
);






CREATE TABLE IF NOT EXISTS healthresponse (
  status VARCHAR(255) NOT NULL
);






CREATE TABLE IF NOT EXISTS rootresponse (
  message VARCHAR(255) NOT NULL
);






CREATE TABLE IF NOT EXISTS userprofile (
  id UUID PRIMARY KEY NOT NULL
  , userid UUID NOT NULL,
  FOREIGN KEY (userid) REFERENCES user(id)
  , avatarurl VARCHAR(255) NOT NULL
  , bio TEXT NOT NULL
  , preferences TEXT NOT NULL
);






CREATE TABLE IF NOT EXISTS user (
  id UUID PRIMARY KEY NOT NULL
  , email VARCHAR(255) NOT NULL
  , passwordhash VARCHAR(255) NOT NULL
  , fullname VARCHAR(255) NOT NULL
  , roleid UUID NOT NULL,
  FOREIGN KEY (roleid) REFERENCES role(id)
  , isactive TEXT NOT NULL
  , destinationid UUID NOT NULL
  , createdat TIMESTAMP NOT NULL
  , updatedat TIMESTAMP NOT NULL
);


CREATE TABLE IF NOT EXISTS user_history (
  history_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  entity_id UUID NOT NULL,
  operation TEXT NOT NULL,
  old_data JSONB,
  new_data JSONB,
  changed_by TEXT,
  changed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS trg_audit_user ON user;
CREATE TRIGGER trg_audit_user
AFTER INSERT OR UPDATE OR DELETE ON user
FOR EACH ROW EXECUTE FUNCTION fn_audit_log();





CREATE TABLE IF NOT EXISTS role (
  id UUID PRIMARY KEY NOT NULL
  , name VARCHAR(255) NOT NULL
  , description VARCHAR(255) NOT NULL
  , permissions TEXT NOT NULL
);






CREATE TABLE IF NOT EXISTS auditlog (
  id UUID PRIMARY KEY NOT NULL
  , entitytype VARCHAR(255) NOT NULL
  , entityid UUID NOT NULL
  , action VARCHAR(255) NOT NULL
  , oldvalue TEXT NOT NULL
  , newvalue TEXT NOT NULL
  , changedby UUID NOT NULL
  , changedat TIMESTAMP NOT NULL
  , ipaddress VARCHAR(255) NOT NULL
);






