// Code generated by core-cli. DO NOT EDIT.

// RBAC guard components derived from schema roles.
'use client';

import React from 'react';

function getUserRoles(): string[] {
  if (typeof window === 'undefined') return [];
  try {
    const token = localStorage.getItem('auth_token');
    if (!token) return [];
    const payload = JSON.parse(atob(token.split('.')[1]));
    // Support both new format (role: string) and legacy format (roles: string[])
    return payload.roles || (payload.role ? [payload.role] : []);
  } catch {
    return [];
  }
}

export function RoleGuard({ roles, children }: { roles: string[]; children: React.ReactNode }) {
  const userRoles = getUserRoles();
  const hasRole = roles.some(r => userRoles.includes(r));

  if (!hasRole) {
    if (process.env.NODE_ENV === 'development') {
      console.debug('[RoleGuard] required roles:', roles, 'user roles:', userRoles);
    }
    return null;
  }

  return <>{children}</>;
}

export function AdminGuard({ children }: { children: React.ReactNode }) {
  return <RoleGuard roles={['admin']}>{children}</RoleGuard>;
}

export function Admin_destinoGuard({ children }: { children: React.ReactNode }) {
  return <RoleGuard roles={['admin_destino']}>{children}</RoleGuard>;
}

export function Gestor_destinoGuard({ children }: { children: React.ReactNode }) {
  return <RoleGuard roles={['gestor_destino']}>{children}</RoleGuard>;
}

export function ConsultorGuard({ children }: { children: React.ReactNode }) {
  return <RoleGuard roles={['consultor']}>{children}</RoleGuard>;
}

export function AuditorGuard({ children }: { children: React.ReactNode }) {
  return <RoleGuard roles={['auditor']}>{children}</RoleGuard>;
}

export function Gestor_regionalGuard({ children }: { children: React.ReactNode }) {
  return <RoleGuard roles={['gestor_regional']}>{children}</RoleGuard>;
}

export function Gestor_nacionalGuard({ children }: { children: React.ReactNode }) {
  return <RoleGuard roles={['gestor_nacional']}>{children}</RoleGuard>;
}

