-- Code generated by core-cli. DO NOT EDIT.

-- Entity tables for evaluations-service
-- This script is run by the postgres container on first startup.
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Generic audit log function
CREATE OR REPLACE FUNCTION fn_audit_log() RETURNS TRIGGER AS $$
BEGIN
  EXECUTE format('INSERT INTO %I_history (entity_id, operation, old_data, new_data, changed_by) VALUES ($1, $2, $3, $4, $5)', TG_TABLE_NAME)
  USING COALESCE(NEW.id, OLD.id), TG_OP, row_to_json(OLD), row_to_json(NEW), current_setting('audit.user_id', true);
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;


CREATE TABLE IF NOT EXISTS healthresponse (
  status VARCHAR(255) NOT NULL
);






CREATE TABLE IF NOT EXISTS rootresponse (
  message VARCHAR(255) NOT NULL
);






CREATE TABLE IF NOT EXISTS subnationallevel (
  id UUID PRIMARY KEY NOT NULL
  , country VARCHAR(255) NOT NULL
  , name VARCHAR(255) NOT NULL
);






CREATE TABLE IF NOT EXISTS destinationtypology (
  id UUID PRIMARY KEY NOT NULL
  , name VARCHAR(255) NOT NULL
);






CREATE TABLE IF NOT EXISTS populationrange (
  id UUID PRIMARY KEY NOT NULL
  , name VARCHAR(255) NOT NULL
);






CREATE TABLE IF NOT EXISTS region (
  id UUID PRIMARY KEY NOT NULL
  , name VARCHAR(255) NOT NULL
  , description VARCHAR(255) NOT NULL
);






CREATE TABLE IF NOT EXISTS membertype (
  id UUID PRIMARY KEY NOT NULL
  , name VARCHAR(255) NOT NULL
);






CREATE TABLE IF NOT EXISTS responsiblearea (
  id UUID PRIMARY KEY NOT NULL
  , name VARCHAR(255) NOT NULL
  , description VARCHAR(255) NOT NULL
);






CREATE TABLE IF NOT EXISTS axislevel (
  id UUID PRIMARY KEY NOT NULL
  , axis VARCHAR(255) NOT NULL
  , objectivepercent TEXT NOT NULL
  , sortorder INTEGER NOT NULL
);






CREATE TABLE IF NOT EXISTS scope (
  id UUID PRIMARY KEY NOT NULL
  , axis VARCHAR(255) NOT NULL
  , acronym VARCHAR(255) NOT NULL
  , name VARCHAR(255) NOT NULL
  , description VARCHAR(255) NOT NULL
  , icon VARCHAR(255) NOT NULL
  , sortorder INTEGER NOT NULL
);






CREATE TABLE IF NOT EXISTS requirement (
  id UUID PRIMARY KEY NOT NULL
  , scopeid UUID NOT NULL
  , code VARCHAR(255) NOT NULL
  , name VARCHAR(255) NOT NULL
  , description VARCHAR(255) NOT NULL
);






CREATE TABLE IF NOT EXISTS indicator (
  id UUID PRIMARY KEY NOT NULL
  , requirementid UUID NOT NULL
  , code VARCHAR(255) NOT NULL
  , name VARCHAR(255) NOT NULL
  , description VARCHAR(255) NOT NULL
  , type VARCHAR(255) NOT NULL
  , criteria TEXT NOT NULL
  , createdat TIMESTAMP NOT NULL
  , updatedat TIMESTAMP NOT NULL
);






CREATE TABLE IF NOT EXISTS evaluation (
  id UUID PRIMARY KEY NOT NULL
  , destinationid UUID NOT NULL
  , name VARCHAR(255) NOT NULL
  , type VARCHAR(255) NOT NULL
  , status VARCHAR(255) NOT NULL
  , startdate TEXT NOT NULL
  , enddate TEXT NOT NULL
  , hasexternalevaluator TEXT NOT NULL
  , promotedfromid UUID NOT NULL
  , createdby UUID NOT NULL
  , createdat TIMESTAMP NOT NULL
  , updatedat TIMESTAMP NOT NULL
);






CREATE TABLE IF NOT EXISTS destination (
  id UUID PRIMARY KEY NOT NULL
  , name VARCHAR(255) NOT NULL
  , country VARCHAR(255) NOT NULL
  , subnationallevelid UUID NOT NULL
  , typologyid UUID NOT NULL
  , populationrangeid UUID NOT NULL
  , regionid UUID NOT NULL
  , membertypeid UUID NOT NULL
  , lat TEXT NOT NULL
  , lng TEXT NOT NULL
  , isadhered TEXT NOT NULL
  , createdat TIMESTAMP NOT NULL
  , updatedat TIMESTAMP NOT NULL
);






