// Code generated by core-cli. DO NOT EDIT.

import { LoginRequest, LoginResponse, RegisterRequest, HealthResponse, RootResponse, UserProfile, User, Role, AuditLog } from './types';

export async function postAuthLogin(body: LoginRequest): Promise<LoginResponse> {
  const response = await fetch('/auth/login', {
    method: 'POST',
    body: JSON.stringify(body),
    headers: {
      'Content-Type': 'application/json',
    },
  });

  return response.json();
}

export async function postAuthRegister(body: RegisterRequest): Promise<User> {
  const response = await fetch('/auth/register', {
    method: 'POST',
    body: JSON.stringify(body),
    headers: {
      'Content-Type': 'application/json',
    },
  });

  return response.json();
}

export async function getUsers(): Promise<User[]> {
  const response = await fetch('/users', {
    method: 'GET',
    
    headers: {
      'Content-Type': 'application/json',
    },
  });

  return response.json();
}

export async function getUsers{id}(): Promise<User> {
  const response = await fetch('/users/{id}', {
    method: 'GET',
    
    headers: {
      'Content-Type': 'application/json',
    },
  });

  return response.json();
}

export async function postUsers(body: User): Promise<User> {
  const response = await fetch('/users', {
    method: 'POST',
    body: JSON.stringify(body),
    headers: {
      'Content-Type': 'application/json',
    },
  });

  return response.json();
}

export async function putUsers{id}(body: User): Promise<User> {
  const response = await fetch('/users/{id}', {
    method: 'PUT',
    body: JSON.stringify(body),
    headers: {
      'Content-Type': 'application/json',
    },
  });

  return response.json();
}

export async function deleteUsers{id}(): Promise<void> {
  const response = await fetch('/users/{id}', {
    method: 'DELETE',
    
    headers: {
      'Content-Type': 'application/json',
    },
  });

  return;
}

export async function getProfile(): Promise<User> {
  const response = await fetch('/profile', {
    method: 'GET',
    
    headers: {
      'Content-Type': 'application/json',
    },
  });

  return response.json();
}

export async function putProfile(body: UserProfile): Promise<UserProfile> {
  const response = await fetch('/profile', {
    method: 'PUT',
    body: JSON.stringify(body),
    headers: {
      'Content-Type': 'application/json',
    },
  });

  return response.json();
}

export async function getRoles(): Promise<Role[]> {
  const response = await fetch('/roles', {
    method: 'GET',
    
    headers: {
      'Content-Type': 'application/json',
    },
  });

  return response.json();
}

export async function postRoles(body: Role): Promise<Role> {
  const response = await fetch('/roles', {
    method: 'POST',
    body: JSON.stringify(body),
    headers: {
      'Content-Type': 'application/json',
    },
  });

  return response.json();
}

export async function getAudit-logs(): Promise<AuditLog[]> {
  const response = await fetch('/audit-logs', {
    method: 'GET',
    
    headers: {
      'Content-Type': 'application/json',
    },
  });

  return response.json();
}


