// Code generated by core-cli. DO NOT EDIT.

export const Roles = {
  ADMIN: 'admin',
  ADMIN_DESTINO: 'admin_destino',
  GESTOR_DESTINO: 'gestor_destino',
  CONSULTOR: 'consultor',
  AUDITOR: 'auditor',
  GESTOR_REGIONAL: 'gestor_regional',
  GESTOR_NACIONAL: 'gestor_nacional',
};

export const Permissions = {
};
