// Code generated by core-cli. DO NOT EDIT.

import { z } from 'zod';

export const LoginRequestSchema = z.object({
  Email: z.string(),
  Password: z.string(),
});

export const LoginResponseSchema = z.object({
  Token: z.string(),
  User: z.string().uuid(),
  Role: z.string(),
  DestinationID: z.string().uuid(),
  Permissions: z.any(),
});

export const RegisterRequestSchema = z.object({
  Email: z.string(),
  Password: z.string(),
  FullName: z.string(),
});

export const HealthResponseSchema = z.object({
  Status: z.string(),
});

export const RootResponseSchema = z.object({
  Message: z.string(),
});

export const UserProfileSchema = z.object({
  ID: z.string().uuid(),
  UserID: z.string().uuid(),
  AvatarURL: z.string(),
  Bio: z.any(),
  Preferences: z.any(),
});

export const UserSchema = z.object({
  ID: z.string().uuid(),
  Email: z.string(),
  PasswordHash: z.string(),
  FullName: z.string(),
  RoleID: z.string().uuid(),
  IsActive: z.any(),
  DestinationID: z.string().uuid(),
  CreatedAt: z.string(),
  UpdatedAt: z.string(),
});

export const RoleSchema = z.object({
  ID: z.string().uuid(),
  Name: z.string(),
  Description: z.string(),
  Permissions: z.any(),
});

export const AuditLogSchema = z.object({
  ID: z.string().uuid(),
  EntityType: z.string(),
  EntityID: z.string().uuid(),
  Action: z.string(),
  OldValue: z.any(),
  NewValue: z.any(),
  ChangedBy: z.string().uuid(),
  ChangedAt: z.string(),
  IPAddress: z.string(),
});


