// Code generated by core-cli. DO NOT EDIT.

export interface LoginRequest {
  Email: string;
  Password: string;
}

export interface LoginResponse {
  Token: string;
  User: string;
  Role: string;
  DestinationID: string;
  Permissions: json;
}

export interface RegisterRequest {
  Email: string;
  Password: string;
  FullName: string;
}

export interface HealthResponse {
  Status: string;
}

export interface RootResponse {
  Message: string;
}

export interface UserProfile {
  ID: string;
  UserID: string;
  AvatarURL: string;
  Bio: text;
  Preferences: json;
}

export interface User {
  ID: string;
  Email: string;
  PasswordHash: string;
  FullName: string;
  RoleID: string;
  IsActive: boolean;
  DestinationID: string;
  CreatedAt: string;
  UpdatedAt: string;
}

export interface Role {
  ID: string;
  Name: string;
  Description: string;
  Permissions: json;
}

export interface AuditLog {
  ID: string;
  EntityType: string;
  EntityID: string;
  Action: string;
  OldValue: json;
  NewValue: json;
  ChangedBy: string;
  ChangedAt: string;
  IPAddress: string;
}


